"""Mock LLM backend for dry-run testing.

Generates deterministic actions based on current state, producing
complete valid trace JSONL without calling any real API.
"""

from __future__ import annotations

import json
from typing import Any, Dict, List, Optional


class MockLLMBackend:
    """Deterministic fake LLM for testing and dry-run mode.

    Produces valid trace JSONL without consuming API tokens.
    Inspects the current agent's state and returns appropriate actions:
    - list_directory if nothing has been listed yet
    - read_text_file for required files not yet read
    - write_file when research is complete
    - handoff_to_analyst to transfer control
    - final to terminate
    """

    def __init__(self):
        self._task = ""
        self._agent_name = "researcher"
        self._mcp_tools: List[str] = []
        self._system_prompt = ""

    def reset(
        self,
        task: str = "",
        agent_name: str = "researcher",
        mcp_tools: List[str] = None,
        system_prompt: str = "",
    ) -> None:
        self._task = task
        self._agent_name = agent_name
        self._mcp_tools = mcp_tools or []
        self._system_prompt = system_prompt

    def generate(self, prompt: str) -> str:
        """Generate a response from the prompt."""
        return self._generate(prompt)

    def _generate(self, prompt: str) -> str:
        """Generate a mock response based on prompt content."""
        # Simple state detection from prompt content
        prompt_lower = prompt.lower()

        # Detect if we're in analyst mode
        if "analyst" in prompt_lower or "handoff" in prompt_lower:
            if self._agent_name == "analyst":
                # Analyst: write a report
                return json.dumps({
                    "reasoning": "Writing comprehensive analysis report",
                    "action": "write_file",
                    "action_input": {
                        "path": "output/financial_summary.md",
                        "content": "# Financial Analysis Report\n\n## Summary\nQ3 revenue: $1,520,000. Net profit margin: 13.8%.\n\n## Findings\n- Revenue exceeded guidance\n- Costs under control\n\n*Generated by mock backend.*",
                    },
                    "final_response": "",
                })

        # Researcher: list directory first
        if "nothing done yet" in prompt_lower or "nothing done" in prompt_lower:
            return json.dumps({
                "reasoning": "Need to discover workspace contents",
                "action": "list_directory",
                "action_input": {"path": "."},
                "final_response": "",
            })

        # Researcher: read files
        if "files discovered" in prompt_lower or "files reviewed" not in prompt_lower:
            return json.dumps({
                "reasoning": "Reading source files to understand the data",
                "action": "read_text_file",
                "action_input": {"path": "documents/q3_financial_data.md"},
                "final_response": "",
            })

        # After reading files, hand off to analyst
        if "files reviewed" in prompt_lower and "write attempts" in prompt_lower:
            if "0" in prompt_lower.split("write attempts")[1][:5]:
                return json.dumps({
                    "reasoning": "Analysis complete, handing off to analyst",
                    "action": "handoff_to_analyst",
                    "action_input": {},
                    "final_response": "",
                })

        # Default: continue exploring
        return json.dumps({
            "reasoning": "Continuing to gather information",
            "action": "list_directory",
            "action_input": {"path": "documents"},
            "final_response": "",
        })

    def parse_action(self, raw_response: str) -> Optional[Dict[str, Any]]:
        """Parse the mock response into an action."""
        try:
            data = json.loads(raw_response)
            return {
                "reasoning": str(data.get("reasoning", "")),
                "action": str(data["action"]),
                "action_input": json.dumps(data.get("action_input", {})),
                "final_response": str(data.get("final_response", "")),
            }
        except (json.JSONDecodeError, KeyError):
            return None

    def _call_api(self, messages: List[Dict[str, Any]], max_tokens: Optional[int] = None) -> str:
        return self._generate(messages[-1].get("content", "") if messages else "")
